language: cpp
compiler: gcc

before_install:
    - pip install --user cpp-coveralls

script:
    - rm -rf build
    - mkdir build
    - cd build
    - cmake ..

script:
    - cmake --build .
    - ctest .

after_success:
    - coveralls --exclude build/CMakeFiles/ --gcov "llvm-cov gcov" --gcov-options '\-lp'  -r ..