language: cpp
compiler: clang

before_install:
    - pip install --user cpp-coveralls

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - cd ..

script:
  - cmake -H. -Bbuild -DCOVERAGE=1
  - cd build
  - cmake --build .
  - ctest

after_success:
  - coveralls --exclude build --exclude test --root .. -E ".*external.*" -E ".*CMakeFiles.*"