language: cpp
compiler: gcc

before_install:
    - pip install --user cpp-coveralls

script:
        - cmake -DCOVERAGE=1 .
        - cmake --build .
        - make test

after_success:
  - coveralls --exclude build --exclude test --root .. -E ".*external.*" -E ".*CMakeFiles.*"