language: cpp
compiler: gcc

before_install:
    - pip install --user cpp-coveralls

script:
  - cmake -H. -Bbuild
  - cd build
  - cmake --build .
  - ctest

after_success:
  - coveralls --exclude build --exclude tests --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"