language: cpp
compiler: gcc

before_install:
    - pip install --user cpp-coveralls

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - cd ..

script:

          - cd build
          - cmake --build .
          - ctest .
          - ctest -T memcheck .

after_success:
  - coveralls --exclude build/CMakeFiles/ --exclude build/gtest/ --gcov "llvm-cov gcov" --gcov-options '\-lp'
