language: cpp
compiler: gcc

before_install:
    - pip install --user cpp-coveralls

script:
      - rm -rf build
      - mkdir build
      - cd build
      - cmake -DCOVERAGE=1 .
      - make
      - make test

after_success:
  - coveralls --exclude build --exclude test --root .. -E ".*external.*" -E ".*CMakeFiles.*"