language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
    - pip install --user cpp-coveralls

before_script:
  - ./configure --enable-gcov

script:
  - cmake -H. -Bbuild
  - cd build
  - cmake --build .
  - ctest

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*" --gcov-options '\-lp'