language: cpp
compiler: gcc

before_install:
    - pip install --user cpp-coveralls

script:
  - cmake -DCOVERAGE=1 .
  - cd build
  - cmake --build .
  - ./test

after_success:
  - coveralls --exclude build --exclude test --root .. -E ".*external.*" -E ".*CMakeFiles.*"