language: cpp
compiler: gcc

before_install:
    - pip install --user cpp-coveralls

script:
    - rm -rf build
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test

after_success:
    - coveralls --gcov-options '\-lp'